services:
  - type: web
    name: weticket-backend
    env: node
    plan: free
    buildCommand: npm install --prefix backend && npm run db:generate --prefix backend
    startCommand: npx prisma migrate deploy --schema=backend/prisma/schema.prisma && npm run db:seed --prefix backend && npm run start --prefix backend
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false 
      - key: DIRECT_URL
        sync: false 
      - key: JWT_ACCESS_SECRET
        generateValue: true 
      - key: JWT_REFRESH_SECRET
        generateValue: true 
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 7d

  - type: web
    name: weticket-frontend
    env: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 